server:
    port: 8080

spring:
    application:
        name: demoGraphql

    datasource:
        url: jdbc:h2:mem:movieapp;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
    graphql:
        graphiql:
            enabled: true
            path: /graphiql
        schema:
            printer:
                enabled: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        org.springframework.graphql: DEBUG